import BaseClient from "./baseClient";
import { Entity, Employee } from "../../types/api";

const mockEmployees: Employee[] = [
  {
    id: "1",
    portrait: "https://c8.alamy.com/comp/HFCJAH/official-portrait-sgt-bianca-burgos-crime-prevention-officer-joint-HFCJAH.jpg",
    firstName: "Jane",
    middleName: "Marie",
    lastName: "Smith",
    nickName: "Janie",
    titleName: "Sergeant",
    gender: "Female",
    Ethnicity: "Hispanic or Latino",
    salary: 30019.2,
    complaints: 3,
    sustainedComplaints: 2,
    pendingComplaints: 1,
    commendations: 1,
    department: "Crime Prevention",
    position: "Officer",
    positionTitle: "Crime Prevention Officer",
    dateHired: "2015-06-15",
    certifiedOfficer: true,
    currentlyEmployed: true,
    accrualProfile: "Full-time"
  },
  {
    id: "2",
    firstName: "John",
    middleName: "Edward",
    lastName: "Doe",
    nickName: "Johnny",
    gender: "Male",
    Ethnicity: "White",
    salary: 20000.0,
    complaints: 2,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 2,
    department: "Traffic",
    position: "Officer",
    positionTitle: "Traffic Enforcement Officer",
    dateHired: "2018-03-12",
    certifiedOfficer: false,
    currentlyEmployed: true,
    accrualProfile: "Part-time"
  },
  {
    id: "3",
    firstName: "Morgan",
    middleName: "Lee",
    lastName: "Johnson",
    titleName: "Lieutenant",
    gender: "Male",
    Ethnicity: "Hispanic or Latino",
    salary: 45000.0,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 4,
    department: "Operations",
    position: "Supervisor",
    positionTitle: "Operations Supervisor",
    dateHired: "2012-11-20",
    certifiedOfficer: true,
    currentlyEmployed: true,
    accrualProfile: "Full-time"
  },
  {
    id: "4",
    firstName: "Josh",
    middleName: "Aaron",
    lastName: "Duck",
    titleName: "Detective",
    gender: "Male",
    Ethnicity: "Hispanic or Latino",
    salary: 45000.0,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 4,
    department: "Investigations",
    position: "Detective",
    positionTitle: "Homicide Detective",
    dateHired: "2010-07-10",
    separationDate: "2023-01-01",
    certifiedOfficer: true,
    currentlyEmployed: false,
    accrualProfile: "Full-time"
  },
  {
    id: "5",
    firstName: "Alecia",
    middleName: "Grace",
    lastName: "Backfield",
    nickName: "Ally",
    titleName: "Officer",
    gender: "Female",
    Ethnicity: "Asian or Pacific Islander",
    salary: 34259.3,
    complaints: 0,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 2,
    department: "Patrol",
    position: "Patrol Officer",
    positionTitle: "Patrol Officer",
    dateHired: "2019-09-05",
    certifiedOfficer: true,
    currentlyEmployed: true,
    accrualProfile: "Full-time"
  }
];

const bedfordEmployees: Employee[] = [
  {
    id: "1",
    employeeId: null,
    titleName: null,
    firstName: "akesa",
    lastName: "AFUHAAMANGO",
    middleName: null,
    nickName: null,
    department: "police department",
    position: "Technician - Kennel",
    positionTitle: "Animal Control Officer",
    Ethnicity: "Native Hawaiian or Other Pacific Islander ",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-02-14",
    separationDate: null,
    salary: 40019.2,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: 3,
    sustainedComplaints: 3,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "2",
    employeeId: null,
    titleName: null,
    firstName: "mark",
    lastName: "AGUIRRE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2019-01-02",
    separationDate: null,
    salary: 82971.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "3",
    employeeId: null,
    titleName: null,
    firstName: "kacie",
    lastName: "ALLEN",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Technician - Property and Evidence",
    positionTitle: "Property Technician",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2013-12-18",
    separationDate: null,
    salary: 52457.6,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "4",
    employeeId: null,
    titleName: null,
    firstName: "jordan",
    lastName: "ALLISON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Police Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-12-14",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "5",
    employeeId: null,
    titleName: null,
    firstName: "mary",
    lastName: "ANDERSON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Analyst - Crime Scene",
    positionTitle: "Crime Analyst",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-09-02",
    separationDate: null,
    salary: 61484.8,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "6",
    employeeId: null,
    titleName: null,
    firstName: "amelia",
    lastName: "ARBELAEZ",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-01-08",
    separationDate: null,
    salary: 50627.2,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "7",
    employeeId: null,
    titleName: null,
    firstName: "megan",
    lastName: "ARD",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Police Recruit",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-03-18",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "8",
    employeeId: null,
    titleName: null,
    firstName: "adriana",
    lastName: "ARREOLA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2005-09-22",
    separationDate: null,
    salary: 69680.0,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "9",
    employeeId: null,
    titleName: null,
    firstName: "cheyenne",
    lastName: "BAKER",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-09-03",
    separationDate: null,
    salary: 50627.2,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "10",
    employeeId: null,
    titleName: null,
    firstName: "keith",
    lastName: "BAUMAN",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Investigator",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-01-10",
    separationDate: null,
    salary: 41399.28,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "11",
    employeeId: null,
    titleName: null,
    firstName: "clayton",
    lastName: "BAXLEY",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Corporal",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2010-07-13",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 2,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "12",
    employeeId: null,
    titleName: null,
    firstName: "jennifer",
    lastName: "BELLINGHAUSEN",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Administrative Assistant - Police",
    positionTitle: "Administrative Assistant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2006-11-02",
    separationDate: null,
    salary: 64708.8,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "13",
    employeeId: null,
    titleName: null,
    firstName: "amy",
    lastName: "BOUNYASANE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Technician - Police Records",
    positionTitle: "Records Technician",
    Ethnicity: "Asian (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-09-30",
    separationDate: null,
    salary: 40560.0,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "14",
    employeeId: null,
    titleName: null,
    firstName: "brett",
    lastName: "BOWEN",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Sergeant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2004-02-05",
    separationDate: null,
    salary: 114566.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "15",
    employeeId: null,
    titleName: null,
    firstName: "LAUREN",
    lastName: "BRESE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Technician - Crime Scene",
    positionTitle: null,
    Ethnicity: "Two or More Races (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-06-03",
    separationDate: null,
    salary: 53040.0,
    certifiedOfficer: false,
    currentlyEmployed: null,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: null,
    commendations: null
  },
  {
    id: "16",
    employeeId: null,
    titleName: null,
    firstName: "jaylin",
    lastName: "BROOKS",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Black or African American (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-02-17",
    separationDate: null,
    salary: 77084.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "17",
    employeeId: null,
    titleName: null,
    firstName: "stephanie",
    lastName: "BUHRKE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2019-12-11",
    separationDate: null,
    salary: 79976.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 4
  },
  {
    id: "18",
    employeeId: null,
    titleName: null,
    firstName: "samantha",
    lastName: "BURRIESCI",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Administrative Assistant - Police",
    positionTitle: "Administrative Assistant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-01-27",
    separationDate: null,
    salary: 43914.0,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "19",
    employeeId: null,
    titleName: null,
    firstName: "julia",
    lastName: "BUTLER",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Supervisor - Police Records",
    positionTitle: "Support Services Supervisor",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2014-06-26",
    separationDate: null,
    salary: 69056.0,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "20",
    employeeId: null,
    titleName: null,
    firstName: "rosanna",
    lastName: "CANTU",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Police Recruit",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-05-01",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "21",
    employeeId: null,
    titleName: null,
    firstName: "deborah",
    lastName: "CARLISLE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Manager - Police",
    positionTitle: "Support Services Manager",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1999-06-21",
    separationDate: null,
    salary: 105624.17,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "22",
    employeeId: null,
    titleName: null,
    firstName: "stephanie",
    lastName: "CARRERA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-04-26",
    separationDate: null,
    salary: 77084.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "23",
    employeeId: null,
    titleName: null,
    firstName: "salvatore",
    lastName: "CARUSO",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Administrative Assistant - Police",
    positionTitle: "Administrative Assistant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2014-12-31",
    separationDate: null,
    salary: 55785.6,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "24",
    employeeId: null,
    titleName: null,
    firstName: "adam",
    lastName: "CASHARA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-11-22",
    separationDate: null,
    salary: 74297.6,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 5
  },
  {
    id: "25",
    employeeId: null,
    titleName: null,
    firstName: "jennifer",
    lastName: "CASTANEDA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Administrative Assistant - Police",
    positionTitle: "Administrative Assistant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2019-12-09",
    separationDate: null,
    salary: 43742.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "26",
    employeeId: null,
    titleName: null,
    firstName: "chad",
    lastName: "CAUDILL",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "School Resource Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-08-23",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "27",
    employeeId: null,
    titleName: null,
    firstName: "CURTIS",
    lastName: "COLE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: null,
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1993-10-14",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: false,
    currentlyEmployed: null,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: null,
    commendations: null
  },
  {
    id: "28",
    employeeId: null,
    titleName: null,
    firstName: "andrew",
    lastName: "CRUMP",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Sergeant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1997-01-03",
    separationDate: null,
    salary: 112424.0,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "29",
    employeeId: null,
    titleName: null,
    firstName: "bradley",
    lastName: "DEUTSCH",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Corporal",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2007-06-04",
    separationDate: null,
    salary: 97593.6,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "30",
    employeeId: null,
    titleName: null,
    firstName: "ignacio",
    lastName: "DIAZ DE LEON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-06-14",
    separationDate: null,
    salary: 77084.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "31",
    employeeId: null,
    titleName: null,
    firstName: "robert",
    lastName: "DICKSON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-12-27",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "32",
    employeeId: null,
    titleName: null,
    firstName: "john",
    lastName: "DISIMONE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-12-13",
    separationDate: null,
    salary: 77084.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 4
  },
  {
    id: "33",
    employeeId: null,
    titleName: null,
    firstName: "joseph",
    lastName: "DORMAN",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2017-05-17",
    separationDate: null,
    salary: 89315.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "34",
    employeeId: null,
    titleName: null,
    firstName: "felipe",
    lastName: "ELIZALDE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-09-16",
    separationDate: null,
    salary: 79976.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 5
  },
  {
    id: "35",
    employeeId: null,
    titleName: null,
    firstName: "DANA",
    lastName: "ERCAY",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: null,
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-08-12",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: false,
    currentlyEmployed: null,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: null,
    commendations: null
  },
  {
    id: "36",
    employeeId: null,
    titleName: null,
    firstName: "william",
    lastName: "EURTO",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Captain - Police",
    positionTitle: "Captain",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2001-11-01",
    separationDate: null,
    salary: 118015.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 4
  },
  {
    id: "37",
    employeeId: null,
    titleName: null,
    firstName: "aida",
    lastName: "FELKER",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Technician - Police Records",
    positionTitle: "Records Technician",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-05-13",
    separationDate: null,
    salary: 35984.0,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "38",
    employeeId: null,
    titleName: null,
    firstName: "amanda",
    lastName: "GARCIA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-05-13",
    separationDate: null,
    salary: 79976.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 4,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 6
  },
  {
    id: "39",
    employeeId: null,
    titleName: null,
    firstName: "oscar",
    lastName: "GARCIA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2012-08-29",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 9
  },
  {
    id: "40",
    employeeId: null,
    titleName: null,
    firstName: "joey",
    lastName: "GAUGER",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Sergeant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1997-03-03",
    separationDate: null,
    salary: 114566.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "41",
    employeeId: null,
    titleName: null,
    firstName: "cameron",
    lastName: "GEORGE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2017-10-25",
    separationDate: null,
    salary: 89315.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 5
  },
  {
    id: "42",
    employeeId: null,
    titleName: null,
    firstName: "ruby",
    lastName: "GEORGE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "School Resource Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2017-04-05",
    separationDate: null,
    salary: 82971.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "43",
    employeeId: null,
    titleName: null,
    firstName: "joshua",
    lastName: "GIBSON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-05-20",
    separationDate: null,
    salary: 50627.2,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "44",
    employeeId: null,
    titleName: null,
    firstName: "emily",
    lastName: "GONZALES",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Police Recruit",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-05-01",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "45",
    employeeId: null,
    titleName: null,
    firstName: "anthony",
    lastName: "GREGORY",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Public Safety Dispatcher",
    positionTitle: "Police Recruit",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2023-01-12",
    separationDate: null,
    salary: 45905.6,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "46",
    employeeId: null,
    titleName: null,
    firstName: "cameron",
    lastName: "GREGORY",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Corporal",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2010-07-13",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "47",
    employeeId: null,
    titleName: null,
    firstName: "samuel",
    lastName: "GULIZIA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-05-18",
    separationDate: null,
    salary: 79976.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 2,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "48",
    employeeId: null,
    titleName: null,
    firstName: "monique",
    lastName: "HALL",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Behavioral Intervention Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2000-05-08",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "49",
    employeeId: null,
    titleName: null,
    firstName: "james",
    lastName: "HAMILTON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Investigator",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2017-05-17",
    separationDate: null,
    salary: 89315.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "50",
    employeeId: null,
    titleName: null,
    firstName: "kwang",
    lastName: "HAN",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Asian (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-12-23",
    separationDate: null,
    salary: 77084.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "51",
    employeeId: null,
    titleName: null,
    firstName: "calvin",
    lastName: "HASKINS",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-02-14",
    separationDate: null,
    salary: 74297.6,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 7
  },
  {
    id: "52",
    employeeId: null,
    titleName: null,
    firstName: "FREEMAN",
    lastName: "HAWKER",
    middleName: null,
    nickName: null,
    department: null,
    position: "Police Officer",
    positionTitle: null,
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-10-15",
    separationDate: null,
    salary: 63606.4,
    certifiedOfficer: false,
    currentlyEmployed: null,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: null,
    commendations: null
  },
  {
    id: "53",
    employeeId: null,
    titleName: null,
    firstName: "ishmel",
    lastName: "HENDERSON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Black or African American (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2017-08-16",
    separationDate: null,
    salary: 89315.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "54",
    employeeId: null,
    titleName: null,
    firstName: "courtney",
    lastName: "HENRY",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Technician - Police Records",
    positionTitle: "Records Technician",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-06-29",
    separationDate: null,
    salary: 40081.6,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "55",
    employeeId: null,
    titleName: null,
    firstName: "alex",
    lastName: "HETLER",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-11-22",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "56",
    employeeId: null,
    titleName: null,
    firstName: "zachary",
    lastName: "HICKS",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Sergeant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2004-12-02",
    separationDate: null,
    salary: 107993.6,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "57",
    employeeId: null,
    titleName: null,
    firstName: "glen",
    lastName: "HLAVINKA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Detective",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1993-10-01",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "58",
    employeeId: null,
    titleName: null,
    firstName: "JAMES",
    lastName: "HUBBARD",
    middleName: null,
    nickName: null,
    department: null,
    position: "Police Officer",
    positionTitle: null,
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2023-06-19",
    separationDate: null,
    salary: 60569.6,
    certifiedOfficer: false,
    currentlyEmployed: null,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: null,
    commendations: null
  },
  {
    id: "59",
    employeeId: null,
    titleName: null,
    firstName: "richard",
    lastName: "HUITT",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "School Resource Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2023-10-30",
    separationDate: null,
    salary: 68998.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "60",
    employeeId: null,
    titleName: null,
    firstName: "scott",
    lastName: "JEFFREY",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2017-01-11",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: 6,
    sustainedComplaints: 3,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "61",
    employeeId: null,
    titleName: null,
    firstName: "anjali",
    lastName: "JOHNSON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2023-08-07",
    separationDate: null,
    salary: 53144.0,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "62",
    employeeId: null,
    titleName: null,
    firstName: "lasedric",
    lastName: "JOHNSON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Investigator",
    Ethnicity: "Black or African American (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2009-03-04",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 4
  },
  {
    id: "63",
    employeeId: null,
    titleName: null,
    firstName: "sarah",
    lastName: "KARNES",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2010-04-14",
    separationDate: null,
    salary: 64355.2,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "64",
    employeeId: null,
    titleName: null,
    firstName: "orapin",
    lastName: "KHAMASA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Police Recruit",
    Ethnicity: "Asian (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-05-01",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "65",
    employeeId: null,
    titleName: null,
    firstName: "robert",
    lastName: "KIDD",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-11-07",
    separationDate: null,
    salary: 79976.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 4
  },
  {
    id: "66",
    employeeId: null,
    titleName: null,
    firstName: "BRITTANY",
    lastName: "LABUS",
    middleName: null,
    nickName: null,
    department: null,
    position: "Technician - Crime Scene",
    positionTitle: null,
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-11-07",
    separationDate: null,
    salary: 49649.6,
    certifiedOfficer: false,
    currentlyEmployed: null,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: null,
    commendations: null
  },
  {
    id: "67",
    employeeId: null,
    titleName: null,
    firstName: "robert",
    lastName: "LAPENNA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Interim Chief - Police",
    positionTitle: "Interim Chief",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2001-03-08",
    separationDate: null,
    salary: 175000.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "68",
    employeeId: null,
    titleName: null,
    firstName: "oscar",
    lastName: "LEDEZMA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2015-12-30",
    separationDate: null,
    salary: 77084.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 4
  },
  {
    id: "69",
    employeeId: null,
    titleName: null,
    firstName: "raymond",
    lastName: "LINDSEY",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "School Resource Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-10-07",
    separationDate: null,
    salary: 68998.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "70",
    employeeId: null,
    titleName: null,
    firstName: "lakeshia",
    lastName: "LOBDELL",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Technician - Crime Scene",
    positionTitle: "Crime Scene Supervisor",
    Ethnicity: "Two or More Races (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2014-10-15",
    separationDate: null,
    salary: 58156.8,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "71",
    employeeId: null,
    titleName: null,
    firstName: "valerie",
    lastName: "LUGO",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Service Officer",
    positionTitle: "Public Service Officer",
    Ethnicity: "Two or More Races (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2019-11-27",
    separationDate: null,
    salary: 41641.6,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "72",
    employeeId: null,
    titleName: null,
    firstName: "veronica",
    lastName: "LUNA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2015-09-23",
    separationDate: null,
    salary: 59030.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "73",
    employeeId: null,
    titleName: null,
    firstName: "seth",
    lastName: "MACADANGDANG",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Police Recruit",
    Ethnicity: "Asian (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-04-15",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "74",
    employeeId: null,
    titleName: null,
    firstName: "ethan",
    lastName: "MACK",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2019-06-03",
    separationDate: null,
    salary: 82971.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 2,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 5
  },
  {
    id: "75",
    employeeId: null,
    titleName: null,
    firstName: "william",
    lastName: "MACK",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Captain - Police",
    positionTitle: "Captain",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1998-07-02",
    separationDate: null,
    salary: 130111.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "76",
    employeeId: null,
    titleName: null,
    firstName: "alexandria",
    lastName: "MAGEE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Animal Control Officer",
    positionTitle: "Animal Contol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-01-10",
    separationDate: null,
    salary: 60299.2,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "77",
    employeeId: null,
    titleName: null,
    firstName: "michael",
    lastName: "MARTIN",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher PT 19 Hours",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2006-06-01",
    separationDate: null,
    salary: 11094.72,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "78",
    employeeId: null,
    titleName: null,
    firstName: "blanca",
    lastName: "MARTINEZ",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Technician - Police Records",
    positionTitle: "Senior Records Technician",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2008-04-07",
    separationDate: null,
    salary: 58177.6,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "79",
    employeeId: null,
    titleName: null,
    firstName: "leslie",
    lastName: "MCDONOUGH",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Sergeant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2009-08-03",
    separationDate: null,
    salary: 104852.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "80",
    employeeId: null,
    titleName: null,
    firstName: "elvis",
    lastName: "MENDOZA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-12-23",
    separationDate: null,
    salary: 79976.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "81",
    employeeId: null,
    titleName: null,
    firstName: "christopher",
    lastName: "MILLER",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2003-02-06",
    separationDate: null,
    salary: 87651.2,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "82",
    employeeId: null,
    titleName: null,
    firstName: "mark",
    lastName: "MILLER",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Sergeant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2010-07-13",
    separationDate: null,
    salary: 114566.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "83",
    employeeId: null,
    titleName: null,
    firstName: "jimmy",
    lastName: "MOODY",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Detective",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1984-07-09",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "84",
    employeeId: null,
    titleName: null,
    firstName: "breeanna",
    lastName: "MOORE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2015-03-25",
    separationDate: null,
    salary: 57969.6,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "85",
    employeeId: null,
    titleName: null,
    firstName: "jose",
    lastName: "MORALES",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Animal Control Supervisor",
    positionTitle: "Animal Control Supervisor",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2023-06-05",
    separationDate: null,
    salary: 73236.8,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "86",
    employeeId: null,
    titleName: null,
    firstName: "todd",
    lastName: "MURPHREE",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Deputy Chief-Police",
    positionTitle: "Deputy Chief",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-07-12",
    separationDate: null,
    salary: 146164.0,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "87",
    employeeId: null,
    titleName: null,
    firstName: "nathan",
    lastName: "NOBLE",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Police Sergeant",
    positionTitle: "Sergeant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2006-07-06",
    separationDate: null,
    salary: 97988.8,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "88",
    employeeId: null,
    titleName: null,
    firstName: "tara",
    lastName: "NOBLE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2005-12-01",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 5
  },
  {
    id: "89",
    employeeId: null,
    titleName: null,
    firstName: "onay",
    lastName: "NUNEZ",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "School Resource Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2010-01-13",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "90",
    employeeId: null,
    titleName: null,
    firstName: "heather",
    lastName: "OLDHAM",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2018-03-11",
    separationDate: null,
    salary: 77084.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 3,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "91",
    employeeId: null,
    titleName: null,
    firstName: "gregory",
    lastName: "PANELLI",
    middleName: null,
    nickName: null,
    department: "police department",
    position: "Police Officer",
    positionTitle: "Warrant Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2007-06-27",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "92",
    employeeId: null,
    titleName: null,
    firstName: "eric",
    lastName: "PEREZ",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2016-09-07",
    separationDate: null,
    salary: 89315.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 2,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: 8
  },
  {
    id: "93",
    employeeId: null,
    titleName: null,
    firstName: "kimberly",
    lastName: "PEREZ",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-08-01",
    separationDate: null,
    salary: 53185.6,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "94",
    employeeId: null,
    titleName: null,
    firstName: "orlando",
    lastName: "PRIETO",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Supervisor",
    positionTitle: "Dispatch Supervisor",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2014-06-04",
    separationDate: null,
    salary: 78020.8,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "95",
    employeeId: null,
    titleName: null,
    firstName: "jeffrey",
    lastName: "PRUETT",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Commercial Vehicle Enforcement Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2007-06-13",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "96",
    employeeId: null,
    titleName: null,
    firstName: "amanda",
    lastName: "RACHAL",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Technician - Crime Scene",
    positionTitle: "Crime Scene Technician",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-05-20",
    separationDate: null,
    salary: 51105.6,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "97",
    employeeId: null,
    titleName: null,
    firstName: "abelardo",
    lastName: "RAMIREZ",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-12-13",
    separationDate: null,
    salary: 77084.8,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "98",
    employeeId: null,
    titleName: null,
    firstName: "david",
    lastName: "REZA",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2020-09-16",
    separationDate: null,
    salary: 79976.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 6
  },
  {
    id: "99",
    employeeId: null,
    titleName: null,
    firstName: "michelle",
    lastName: "RICARD",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1998-11-05",
    separationDate: null,
    salary: 74110.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "100",
    employeeId: null,
    titleName: null,
    firstName: "jonathan",
    lastName: "RICE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Police Recruit",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-09-16",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "101",
    employeeId: null,
    titleName: null,
    firstName: "jason",
    lastName: "RICHER",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Sergeant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2004-07-08",
    separationDate: null,
    salary: 107993.6,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: null,
    pendingComplaints: 1,
    commendations: 1
  },
  {
    id: "102",
    employeeId: null,
    titleName: null,
    firstName: "john",
    lastName: "RIPLEY",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Investigator",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1984-11-13",
    separationDate: null,
    salary: 41399.28,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "103",
    employeeId: null,
    titleName: null,
    firstName: "schnell",
    lastName: "RODGERS",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "Black or African American (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2019-07-03",
    separationDate: null,
    salary: 54766.4,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "104",
    employeeId: null,
    titleName: null,
    firstName: "IVAN",
    lastName: "ROMAN-GUTIERREZ",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: null,
    Ethnicity: "Hispanic or Latino",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2008-11-24",
    separationDate: null,
    salary: 97593.6,
    certifiedOfficer: false,
    currentlyEmployed: null,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: null,
    commendations: null
  },
  {
    id: "105",
    employeeId: null,
    titleName: null,
    firstName: "pilar",
    lastName: "ROPER-FOO",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Police Corporal",
    positionTitle: "Corporal",
    Ethnicity: "Two or More Races (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2018-06-13",
    separationDate: null,
    salary: 88550.18,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "106",
    employeeId: null,
    titleName: null,
    firstName: "nassim",
    lastName: "SAYEGH",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Detective",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-12-12",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "107",
    employeeId: null,
    titleName: null,
    firstName: "noel",
    lastName: "SCOTT",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Captain - Police",
    positionTitle: "Captain",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2004-07-07",
    separationDate: null,
    salary: 130111.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "108",
    employeeId: null,
    titleName: null,
    firstName: "stephen",
    lastName: "SELVIDGE",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Technician - Digital Media Evidence",
    positionTitle: "Digital Media Evidence Coordinator",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2002-02-14",
    separationDate: null,
    salary: 65603.2,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "109",
    employeeId: null,
    titleName: null,
    firstName: "michael",
    lastName: "SHIKANY",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Deputy Chief - Police",
    positionTitle: "Interim Deputy Chief",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1993-10-01",
    separationDate: null,
    salary: 148949.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "110",
    employeeId: null,
    titleName: null,
    firstName: "david",
    lastName: "SMITH",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Lieutenant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1992-01-13",
    separationDate: null,
    salary: 126547.2,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "111",
    employeeId: null,
    titleName: null,
    firstName: "reeyse",
    lastName: "SMITH",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2024-04-15",
    separationDate: null,
    salary: 50627.2,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "112",
    employeeId: null,
    titleName: null,
    firstName: "dennis",
    lastName: "SNYDER",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Black or African American (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2019-12-11",
    separationDate: null,
    salary: 79976.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 4
  },
  {
    id: "113",
    employeeId: null,
    titleName: null,
    firstName: "deidre",
    lastName: "SPEARS",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "Black or African American (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2009-12-13",
    separationDate: null,
    salary: 91998.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "114",
    employeeId: null,
    titleName: null,
    firstName: "matthew",
    lastName: "STILL",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Recruit Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2023-07-03",
    separationDate: null,
    salary: 71614.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "115",
    employeeId: null,
    titleName: null,
    firstName: "tyler",
    lastName: "STILLMAN",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Sergeant",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2000-01-27",
    separationDate: null,
    salary: 114566.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "116",
    employeeId: null,
    titleName: null,
    firstName: "mary",
    lastName: "TARANGO",
    middleName: "ANNE",
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Corporal",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2018-10-22",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 5
  },
  {
    id: "117",
    employeeId: null,
    titleName: null,
    firstName: "karlanita",
    lastName: "TAYLOR",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Administrative Assistant - Police",
    positionTitle: "Administrative Secretary",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2003-01-20",
    separationDate: null,
    salary: 64500.8,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "118",
    employeeId: null,
    titleName: null,
    firstName: "james",
    lastName: "TEEL",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2019-02-27",
    separationDate: null,
    salary: 82971.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 6
  },
  {
    id: "119",
    employeeId: null,
    titleName: null,
    firstName: "brandon",
    lastName: "THOMAS",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Corporal",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2016-11-02",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: 3,
    sustainedComplaints: 3,
    pendingComplaints: 0,
    commendations: 4
  },
  {
    id: "120",
    employeeId: null,
    titleName: null,
    firstName: "mark",
    lastName: "TOOLEY",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Corporal",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2009-04-29",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "121",
    employeeId: null,
    titleName: null,
    firstName: "tate",
    lastName: "TRUEBLOOD",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Police Recruit",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2022-04-18",
    separationDate: null,
    salary: 74297.6,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "122",
    employeeId: null,
    titleName: null,
    firstName: "cinthya",
    lastName: "VILLEGAS",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Executive Assistant",
    positionTitle: "Executive Assistant",
    Ethnicity: "Hispanic or Latino",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2023-02-27",
    separationDate: null,
    salary: 68827.2,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "123",
    employeeId: null,
    titleName: null,
    firstName: "clayton",
    lastName: "WATKINS",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2019-10-09",
    separationDate: null,
    salary: 79976.0,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 9
  },
  {
    id: "124",
    employeeId: null,
    titleName: null,
    firstName: "christopher",
    lastName: "WEST",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Corporal",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1997-07-14",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "125",
    employeeId: null,
    titleName: null,
    firstName: "lena",
    lastName: "WEST",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Investigator",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "1996-01-25",
    separationDate: null,
    salary: 87651.2,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "126",
    employeeId: null,
    titleName: null,
    firstName: "amanda",
    lastName: "WHEELER",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Animal Control Officer",
    positionTitle: "Animal Control Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Female",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2023-11-27",
    separationDate: null,
    salary: 49587.2,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "127",
    employeeId: null,
    titleName: null,
    firstName: "chad",
    lastName: "WILKINSON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Corporal",
    Ethnicity: "Two or More Races (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2017-08-16",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "128",
    employeeId: null,
    titleName: null,
    firstName: "jeffrey",
    lastName: "WILLIAMS",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Chief-Police",
    positionTitle: "Chief",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2021-03-29",
    separationDate: null,
    salary: 182314.82,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "129",
    employeeId: null,
    titleName: null,
    firstName: "scott",
    lastName: "WILLIAMSON",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Corporal",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2010-07-13",
    separationDate: null,
    salary: 100526.4,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "130",
    employeeId: null,
    titleName: null,
    firstName: "james",
    lastName: "WILSON",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: "Public Safety Dispatcher",
    positionTitle: "Dispatcher",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2023-06-26",
    separationDate: null,
    salary: 50627.2,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "131",
    employeeId: null,
    titleName: null,
    firstName: "daniel",
    lastName: "WOOD",
    middleName: null,
    nickName: null,
    department: "POLICE DEPARTMENT",
    position: "Police Officer",
    positionTitle: "Patrol Officer",
    Ethnicity: "White (not Hispanic or Latino)",
    gender: "Male",
    accrualProfile: null,
    employeeStatus: null,
    dateHired: "2016-03-16",
    separationDate: null,
    salary: 89315.2,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "132",
    employeeId: null,
    titleName: null,
    firstName: "R.",
    lastName: "Barnes",
    middleName: null,
    nickName: null,
    department: "Animal Services",
    position: null,
    positionTitle: "Animal Control Officer",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "133",
    employeeId: null,
    titleName: null,
    firstName: "M.",
    lastName: "Bellinghausen",
    middleName: null,
    nickName: null,
    department: "Animal Services",
    position: null,
    positionTitle: "Animal Control Supervisor",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "134",
    employeeId: null,
    titleName: null,
    firstName: "K.",
    lastName: "Bennett",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Mental Health Coordinator",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "135",
    employeeId: null,
    titleName: null,
    firstName: "K.",
    lastName: "Blundell",
    middleName: null,
    nickName: null,
    department: "Animal Services",
    position: null,
    positionTitle: "Animal Control Officer",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "136",
    employeeId: null,
    titleName: null,
    firstName: "T.",
    lastName: "Brannon",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Public Service Officer",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 3
  },
  {
    id: "137",
    employeeId: null,
    titleName: null,
    firstName: "D.",
    lastName: "Campbell",
    middleName: null,
    nickName: null,
    department: "Court",
    position: null,
    positionTitle: "Municipal Court Manager",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "138",
    employeeId: null,
    titleName: null,
    firstName: "K.",
    lastName: "Cole",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Detective",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "139",
    employeeId: null,
    titleName: null,
    firstName: "A.",
    lastName: "Escarsega",
    middleName: null,
    nickName: null,
    department: "Court",
    position: null,
    positionTitle: "Court Clerk",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "140",
    employeeId: null,
    titleName: null,
    firstName: "M.",
    lastName: "Freeman",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Administrative Assistant",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "141",
    employeeId: null,
    titleName: null,
    firstName: "A.",
    lastName: "Hocker",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Patrol Officer",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: 2,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "142",
    employeeId: null,
    titleName: null,
    firstName: "S.",
    lastName: "Jakubik",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Lead Animal Control Officer",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: 1,
    sustainedComplaints: 1,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "145",
    employeeId: null,
    titleName: null,
    firstName: "A.",
    lastName: "James",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Dispatch Supervisor",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "146",
    employeeId: null,
    titleName: null,
    firstName: "C.",
    lastName: "Latta",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Crime Victims' Coordinator",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "147",
    employeeId: null,
    titleName: null,
    firstName: "V.",
    lastName: "Little",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Dispatcher",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "148",
    employeeId: null,
    titleName: null,
    firstName: "M.",
    lastName: "Mason",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Kennel Technician",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: 4,
    sustainedComplaints: 4,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "149",
    employeeId: null,
    titleName: null,
    firstName: "X.",
    lastName: "Meng",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Crime Scene Technician",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "150",
    employeeId: null,
    titleName: null,
    firstName: "N.",
    lastName: "Philip",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Crime Victims' Coordinator",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "151",
    employeeId: null,
    titleName: null,
    firstName: "C.",
    lastName: "Reynolds",
    middleName: null,
    nickName: null,
    department: "Court",
    position: null,
    positionTitle: "Court Clerk",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "152",
    employeeId: null,
    titleName: null,
    firstName: "K.",
    lastName: "Rettig",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Crime Victims' Coordinator",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: false,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  },
  {
    id: "153",
    employeeId: null,
    titleName: null,
    firstName: "I.",
    lastName: "Roman",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Corporal",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: true,
    currentlyEmployed: true,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 2
  },
  {
    id: "154",
    employeeId: null,
    titleName: null,
    firstName: "C.",
    lastName: "Sandoval",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Patrol Officer",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: true,
    currentlyEmployed: false,
    complaints: 1,
    sustainedComplaints: 0,
    pendingComplaints: 0,
    commendations: 1
  },
  {
    id: "155",
    employeeId: null,
    titleName: null,
    firstName: "K.",
    lastName: "Smith",
    middleName: null,
    nickName: null,
    department: "Police Department",
    position: null,
    positionTitle: "Crossing Guard Lead",
    Ethnicity: null,
    gender: null,
    accrualProfile: null,
    employeeStatus: null,
    dateHired: null,
    separationDate: null,
    salary: null,
    certifiedOfficer: false,
    currentlyEmployed: true,
    complaints: null,
    sustainedComplaints: null,
    pendingComplaints: 0,
    commendations: null
  }
]

const mockEntities: Entity[] = [
  {
    id: "1",
    name: "Bedford Police Department",
    phone: "+18179522440",
    address: "2121 L Don Dodson Dr, Bedford, TX 76021",
    website: "https://bedfordtx.gov/174/Police-Department",
    employees: bedfordEmployees,
  },
  {
    id: "2",
    name: "Fort Worth Fire Department",
    phone: "+18179520000",
    address: "123 Main St, Fort Worth, TX 76102",
    website: "https://fortworthtexas.gov/fire/",
    employees: mockEmployees,
  },
  // Add more entities as needed
];

export default class EntitiesClient extends BaseClient {
  
  async getEntities(): Promise<Entity[]> {
    return mockEntities;
    return this.request<Entity[]>('/entities');
  }

  async getEntityById(id: string): Promise<Entity> {
    return mockEntities.filter((entity) => entity.id === id)[0];
    return this.request<Entity>(`/entities/${id}`);
  }
  
  async getEmployeeById(id: string): Promise<Employee> {
    for (const entity of mockEntities) {
      const employee = entity.employees.find((emp) => emp.id === id);
      if (employee) return employee;
    }
    throw new Error(`Employee with id ${id} not found`);
    return this.request<Employee>(`/entities/${id}`);
  }
}
